# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_group', to='otree.Session')),
            ],
            options={
                'db_table': 'RAG_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('person_A_type', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('person_B_type', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('person_C_type', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('person_A_price', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('person_B_price', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('person_C_price', otree.db.models.StringField(choices=[('Gar nicht verantwortlich', 'Gar nicht verantwortlich'), ('Eher nicht verantwortlich', 'Eher nicht verantwortlich'), ('Eher verantwortlich', 'Eher verantwortlich'), ('Sehr verantwortlich', 'Sehr verantwortlich')], max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RAG.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_player', to='otree.Session')),
            ],
            options={
                'db_table': 'RAG_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'RAG_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG.Subsession'),
        ),
    ]
